version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kpos
    volumes:
      - .:/var/www/html
    ports:
      - "8010:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql
    networks:
      - laravel_network
  
  mysql:
    image: mysql:5.7
    container_name: kpos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kpos
    ports:
      - "5308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  npm:
    image: node:14
    container_name: kpos_npm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: tail -f /dev/null
    depends_on:
      - app
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local